### ISSUE TITLE
2PL Latent Regression model formula in stan file

### ISSUE THREAD

**Issue by abhsarma** [danielcfurr/edstan#15]
In the [documentation file for 2PL regression](http://mc-stan.org/users/documentation/case-studies/tutorial_twopl.html), the formula used for the logistic function is:

![codecogseqn](https://user-images.githubusercontent.com/18705902/33270776-2785e814-d353-11e7-9cdb-964c75e9f20c.png)

However, the [formula in the stan file](https://github.com/danielcfurr/edstan/blob/master/inst/extdata/2pl_latent_reg.stan) is:
y ~ bernoulli_logit(alpha[ii].*theta[jj] - beta[ii]);

Which, if I am understanding the stan syntax correctly and considering matrix multiplication between **_alpha_** and **_theta_**, is:

![codecogseqn 1](https://user-images.githubusercontent.com/18705902/33270846-6d6b765a-d353-11e7-8a8e-f9ee694f7d3f.png)

Could you verify if this is correct?

**Comment by danielcfurr** [comment]
Thank you for pointing this out. The issue is that the tutorial you link to is old, and edstan has changed since then. The 
[case study](http://mc-stan.org/users/documentation/case-studies/rasch_and_2pl.html#stan-code-for-the-2pl-with-latent-regression) 
is up to date with edstan, and is a better place to look to for documentation.

**Comment by abhsarma** [comment]
This makes sense. Thanks for the clarification!

**Comment by herbps10** [comment]
Thanks for all your work on this package, I've found it very useful.

I'm wondering if you would mind elaborating on the change described by abhsarma above (I see the change in 2pl_latent_reg.stan happened in a261aa21cb1d660247689bbb9808a405aa81190a)

I'm learning about IRT models and I've been seeing the model expressed as

![model1](https://user-images.githubusercontent.com/18705902/33270776-2785e814-d353-11e7-9cdb-964c75e9f20c.png)

(e.g. Swaminathan 1985) rather than

![model2](https://user-images.githubusercontent.com/18705902/33270846-6d6b765a-d353-11e7-8a8e-f9ee694f7d3f.png)

Just wondering if you could point me in the right direction to understand why the latter is used. Thanks!

**Comment by danielcfurr** [comment]
Hello, Herb, and thanks for your question. I'm always happy to find out
that someone is actually reading those documents!

The two approaches are mathematically equivalent, though maybe the first
way is a little more interpretable. I use the second approach because
sometimes it is much more efficient in Stan. As I understand it,
multiplying parameters together induces a correlation in their posterior
that causes Stan to be less efficient. I can avoid multiplying alpha and
beta, so that's what I do. You CAN do it either way, of course.

Best,
Dan
